api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "b2c-cod-hider"
type = "function"
uid = "2e7a10a7-5bf0-78c9-2b5d-b5993749796db300000e"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/input.graphql"
  export = "cart_payment_methods_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/b2c-cod-hider.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
