# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b2b9198df00ad6154f8735bb9cd2a186"
name = "w-m-functions"
application_url = "https://w-m-functions.julian-c4a.workers.dev"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
