api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "b2b-payment-filter"
type = "function"
uid = "ab13f51b-d2df-2545-c846-587d46e9718751602cd0"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/input.graphql"
  export = "cart_payment_methods_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/b2b_payment_filter.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
